### ISSUE TITLE
Expand main loop for first scenario

### ISSUE THREAD

**Issue by gomezzz** [esa/LADDS#21]
# Feature
## Desired behavior
Run simulation for  some time
## What needs to be done
- [x] Add desired end_time and dt 
- [x] Call I/O input (depends on #22 )
- [x] Call output with simulation results (depends on #22 )
- [ ] Add a test for a minimal scenario (depends on #17 )
- [x] Freeze reference to propagator repo
## How it can be tested
- [ ] Run it!
- [ ] Run the test
